services:
  mysql:
    image: mysql:latest
    volumes:
      - my_sql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret 
    ports:
      - "8001:3306"

volumes:
  my_sql_volume: