"""empty message

Revision ID: 0988a0e81d05
Revises: 14cfd6b08f13
Create Date: 2024-07-08 13:30:18.565951

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0988a0e81d05"
down_revision: Union[str, None] = "14cfd6b08f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tag_association_table")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
