"""empty message

Revision ID: 1657c0f2c9da
Revises: 01f42ea4dd44
Create Date: 2024-07-03 10:30:30.491957

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1657c0f2c9da"
down_revision: Union[str, None] = "01f42ea4dd44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
