"""empty message

Revision ID: 3be7d96c97a3
Revises: 618e003e9565
Create Date: 2024-07-11 10:07:55.885457

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3be7d96c97a3"
down_revision: Union[str, None] = "618e003e9565"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe_images",
        sa.Column("recipe_image_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(100), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.recipe_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_image_id"),
    )
    op.create_table(
        "recipe_tag_association_table",
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.tag_id"],
        ),
    )
    op.add_column("users", sa.Column("profile_pic_path", sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
