"""empty message

Revision ID: a7e421ecc398
Revises: 0c08ce779ce8
Create Date: 2024-07-03 12:28:36.537109

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7e421ecc398"
down_revision: Union[str, None] = "0c08ce779ce8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
