"""empty message

Revision ID: 7ca3e0ca6585
Revises: bf2249d76e56
Create Date: 2024-07-09 08:02:29.709171

"""

from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ca3e0ca6585"
down_revision: Union[str, None] = "bf2249d76e56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.Date(), default=datetime.now(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("prep_time", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("recipe_id"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.user_id"],
        ),
    )
    op.create_table(
        "nutrition_infos",
        sa.Column("nutritio_info_id", sa.Integer()),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("protein", sa.Integer, nullable=False),
        sa.Column("carbohydrates", sa.Integer(), nullable=False),
        sa.Column("sugar", sa.Integer(), nullable=False),
        sa.Column("fiber", sa.Integer(), nullable=False),
        sa.Column("fat", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("nutritio_info_id"),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
    )

    op.create_table(
        "instructions",
        sa.Column("instruction_id", sa.Integer()),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("instruction_id"),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
    )

    op.create_table(
        "units",
        sa.Column("unit_id", sa.Integer()),
        sa.Column("unit", sa.String(100), nullable=False),
        sa.Column("liquid", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("unit_id"),
    )

    op.create_table(
        "ingredientes",
        sa.Column("ingredient_id", sa.Integer()),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient", sa.String(100), nullable=False),
        sa.Column("amount", sa.Float(2), nullable=False),
        sa.Column("unit_id", sa.Integer()),
        sa.PrimaryKeyConstraint("ingredient_id"),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.unit_id"],
        ),
    )

    op.create_table(
        "user_recipe_association_table",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.recipe_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
