"""empty message

Revision ID: 6349bb7a0511
Revises: 14cfd6b08f13
Create Date: 2024-07-05 14:25:52.728744

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6349bb7a0511"
down_revision: Union[str, None] = "14cfd6b08f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
