"""empty message

Revision ID: 14cfd6b08f13
Revises: b2419ed4009a
Create Date: 2024-07-04 15:36:36.846631

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14cfd6b08f13"
down_revision: Union[str, None] = "b2419ed4009a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
