"""empty message

Revision ID: 3d0cfbaa0e89
Revises: a7e421ecc398
Create Date: 2024-07-03 12:32:06.216855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d0cfbaa0e89"
down_revision: Union[str, None] = "a7e421ecc398"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    pass
