"""empty message

Revision ID: 618e003e9565
Revises: 7ca3e0ca6585
Create Date: 2024-07-10 08:06:14.987892

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "618e003e9565"
down_revision: Union[str, None] = "7ca3e0ca6585"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_user_association_table",
        sa.Column("follower_id", sa.Integer(), nullable=True),
        sa.Column("followed_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["followed_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.user_id"],
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
