"""empty message

Revision ID: df7b0c0748b0
Revises: 3be7d96c97a3
Create Date: 2024-07-12 09:50:53.352396

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df7b0c0748b0"
down_revision: Union[str, None] = "3be7d96c97a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "recipe_images",
        "image_path",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "profile_pic_path",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "profile_pic_path",
        existing_type=sa.String(length=300),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "recipe_images",
        "image_path",
        existing_type=sa.String(length=300),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=False,
    )
